import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
const run = (args) => execFileSync('git', args, { cwd: repositoryRoot, encoding: 'utf8' }).trim();
const clean = (value) => value || '_None_';
const lines = (value) => value ? value.split(/\r?\n/).map((line) => `- \`${line}\``).join('\n') : '- _None_';

let branch = 'unknown';
let revision = 'unknown';
let recent = '';
let status = '';

try {
  branch = run(['branch', '--show-current']) || 'detached HEAD';
  revision = run(['log', '-1', '--format=%H%n%ad%n%s', '--date=iso']);
  recent = run(['log', '--oneline', '-5']);
  const unstaged = run(['diff', '--name-status']);
  const staged = run(['diff', '--cached', '--name-status']);
  const untracked = run(['ls-files', '--others', '--exclude-standard'])
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => `?? ${line}`)
    .join('\n');
  const pending = [staged, unstaged, untracked]
    .filter(Boolean)
    .join('\n')
    .split(/\r?\n/)
    .filter(Boolean);
  const localOnly = /^(?:\.agent\/|\.agents\/|\.codex\/|\.cursor\/(?:agents|skills)\/|\.cursor\/hooks\.json|\.github\/(?:agents|hooks|skills)\/|\.impeccable\/critique\/|graphify-out\/|site\/graphify-out\/|site\/tsconfig\.tsbuildinfo$)/;
  status = [...new Set(pending)]
    .filter((line) => {
      const path = line.replace(/^(?:\?\?|[A-Z]+)\s+/, '');
      return path !== 'docs/LLM_HANDOFF.md' && !localOnly.test(path);
    })
    .join('\n');
} catch {
  // The document remains useful if copied outside a Git checkout.
}

const [commit = 'unknown', committedAt = 'unknown', subject = 'unknown'] = revision.split(/\r?\n/);
const output = `# VEEMAP Website — LLM Handoff

> Generated by \`node tools/update-handoff.mjs\`. Regenerate after meaningful
> changes; do not hand-edit the current-state sections below.

## Start here

1. Read [AGENTS.md](../AGENTS.md), [PRODUCT.md](../PRODUCT.md), and
   [site/DESIGN.md](../site/DESIGN.md).
2. For public copy or claims, read the relevant evidence in
   [docs/brand-context](brand-context/README.md).
3. Preserve the pending changes listed below. They are working state, not an
   accepted release.

## Working agreement

- The Ponytail skill is recommended for coding when available. If unavailable,
  continue with the project instructions; installing it is not required.
- Run \`node tools/update-handoff.mjs\` after a meaningful change. The
  versioned pre-commit hook performs the same refresh when hooks are enabled.
- Do not invent facts, certifications, customer claims, or machine performance.
- The enquiry form deliberately opens a prefilled \`mailto:\` message; it is
  not a submitted lead service.

## Current repository state

- Branch: \`${branch}\`
- Base commit when generated: \`${commit}\` — ${subject} (${committedAt})
- Generated: ${new Date().toISOString()}

### Uncommitted work (preserve)

${lines(status)}

### Recent commits

${lines(recent)}

## Architecture map

| Area | Location | Notes |
| --- | --- | --- |
| Public site | \`site/app/\` | Next.js App Router homepage, capability, industry, sector, company, careers and contact pages. |
| Site shell | \`site/app/layout.tsx\` | Metadata, fonts, theme bootstrap. |
| Visual system | \`site/app/globals.css\`, \`site/DESIGN.md\` | Responsive layout, motion presentation, accessibility conventions. |
| Dependencies and checks | \`site/package.json\` | Next.js 16, React 19, GSAP, lint and production build commands. |
| Brand truth | \`docs/brand-context/\` | Source-cited identity, contacts, capability and claim authority. |
| Product requirements | \`PRODUCT.md\` | Audience, conversion goal, constraints and open decisions. |
| CI/CD | \`.github/workflows/ci.yml\`, \`docs/CI_CD.md\`, \`site/vercel.json\` | CI verifies the site; linked Vercel project \`veemap-technologies\` receives Git deployments from \`main\`. |
| Image provenance | \`site/public/**/*.json\` | Keep each shipped raster paired with its provenance file. |

## Commands

From the repository root:

\`\`\`powershell
node tools/install-git-hooks.mjs   # once per checkout
node tools/update-handoff.mjs
\`\`\`

From \`site/\`:

\`\`\`powershell
npm ci
npm run lint
npm run build
\`\`\`

Node.js 22.13 or newer is required.

## Content and UX constraints

- The brand is VEEMAP Technologies, an Indian industrial-automation and
  special-purpose-machine company.
- Ground claims in \`docs/brand-context/\`; approved headline proof includes
  236 projects, 55 clients, and five sectors.
- Support reduced motion and mobile access. Motion must explain engineering,
  not block reading or enquiry capture.
- Do not add a back end, CRM, upload field, or external submission service
  without explicit authorization. Contact details and public facts must come
  from the brand-context documents.
- The current hero machine is conceptual and non-proprietary; retain that
  framing until approved assets arrive.

## Known open decisions

- Lead submission destination, consent wording, and response expectations are
  undecided; the current experience intentionally prepares an email only.
- Official website design rules and production-ready 3D assets have not been
  supplied. The current design evidence is documented, not canonical branding.

## Handoff protocol

Before passing this repository to another LLM, regenerate this document, run
the relevant verification commands, and state what did and did not pass. The
recipient should begin with the three files in **Start here**, then inspect the
current working-tree section before editing.
`;

mkdirSync(resolve(repositoryRoot, 'docs'), { recursive: true });
writeFileSync(resolve(repositoryRoot, 'docs/LLM_HANDOFF.md'), output, 'utf8');
console.log('Updated docs/LLM_HANDOFF.md');
